# BellaBeat Case Study

BellaBeat is a high-tech manufacturer of health-focused products for women. Although they are a successful small company, there is room for growth in the expanding smart device market. Urška Sršen is Bellabeat’s cofounder and Chief Creative Officer while, Sando Mur is Bellabeat’s other cofounder, mathematician and key member of the Bellabeat executive team.

**Business Task**
My mission is to analyze smart device usage data and report my findings to my fellow BellaBeat market team members.

**Questions to Answer**
- What trends do we see in smart device wearers?
- What can these trends tell us about growth potential in the smart device market?
- How can BellaBeat capitalize on the areas in the smart device market that are currently underutilized?

## Preparation

#### Load the appropriate libraries


In [1]:
import numpy as np
import pandas as pd
import plotly.express  as px
import plotly.graph_objects as go
import glob 
from datetime import datetime


#### Load the files

In [2]:
files = glob.glob('../data/Fitabase Data 4.12.16-5.12.16/*')
dailyActivity_merged = pd.read_csv(files[0])
dailyCalories_merged = pd.read_csv(files[1])
dailyIntensities_merged = pd.read_csv(files[2])
dailySteps_merged = pd.read_csv(files[3])
heartrate_seconds_merged = pd.read_csv(files[4])
hourlyCalories_merged = pd.read_csv(files[5])
hourlyIntensities_merged = pd.read_csv(files[6])
hourlySteps_merged = pd.read_csv(files[7])
minuteCaloriesNarrow_merged = pd.read_csv(files[8])
minuteCaloriesWide_merged = pd.read_csv(files[9])
minuteIntensitiesNarrow_merged = pd.read_csv(files[10])
minuteIntensitiesWide_merged = pd.read_csv(files[11])
minuteMETsNarrow_merged = pd.read_csv(files[12])
minuteSleep_merged = pd.read_csv(files[13])
minuteStepsNarrow_merged = pd.read_csv(files[14])
minuteStepsWide_merged = pd.read_csv(files[15])
sleepDay_merged = pd.read_csv(files[16])
weightLogInfo_merged = pd.read_csv(files[17])


#### Get a quick summary of structure and content of each files


In [3]:
# Create a function to help show relevant information
def pstr(df):
    # return df.info(null_counts=True, verbose=True), df.apply(lambda x: [x.unique()]), df.describe()
    print(df.info(null_counts=True, verbose=True))
    display(df.apply(lambda x: [x.unique()[:5]]).T)
    display(df.describe())

In [4]:
pstr(dailyActivity_merged)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 940 entries, 0 to 939
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Id                        940 non-null    int64  
 1   ActivityDate              940 non-null    object 
 2   TotalSteps                940 non-null    int64  
 3   TotalDistance             940 non-null    float64
 4   TrackerDistance           940 non-null    float64
 5   LoggedActivitiesDistance  940 non-null    float64
 6   VeryActiveDistance        940 non-null    float64
 7   ModeratelyActiveDistance  940 non-null    float64
 8   LightActiveDistance       940 non-null    float64
 9   SedentaryActiveDistance   940 non-null    float64
 10  VeryActiveMinutes         940 non-null    int64  
 11  FairlyActiveMinutes       940 non-null    int64  
 12  LightlyActiveMinutes      940 non-null    int64  
 13  SedentaryMinutes          940 non-null    int64  
 14  Calories  

C:\Users\User\AppData\Local\Temp\ipykernel_14676\3310633354.py:4: FutureWarning: null_counts is deprecated. Use show_counts instead
  print(df.info(null_counts=True, verbose=True))


0
Id                        [1503960366, 1624580081, 1644430081, 184450507...
ActivityDate              [4/12/2016, 4/13/2016, 4/14/2016, 4/15/2016, 4...
TotalSteps                               [13162, 10735, 10460, 9762, 12669]
TotalDistance             [8.5, 6.96999979019165, 6.73999977111816, 6.28...
TrackerDistance           [8.5, 6.96999979019165, 6.73999977111816, 6.28...
LoggedActivitiesDistance  [0.0, 1.95959603786469, 4.08169221878052, 2.78...
VeryActiveDistance        [1.87999999523163, 1.57000005245209, 2.4400000...
ModeratelyActiveDistance  [0.550000011920929, 0.689999997615814, 0.40000...
LightActiveDistance       [6.05999994277954, 4.71000003814697, 3.9100000...
SedentaryActiveDistance   [0.0, 0.0099999997764825, 0.0199999995529652, ...
VeryActiveMinutes                                      [25, 21, 30, 29, 36]
FairlyActiveMinutes                                    [13, 19, 11, 34, 10]
LightlyActiveMinutes                              [328, 217, 181, 209, 221]
SedentaryMinutes                                 [728, 776, 1218, 726, 773]
Calories                                     [1985, 1797, 1776, 1745, 1863]

Id    TotalSteps  TotalDistance  TrackerDistance  \
count  9.400000e+02    940.000000     940.000000       940.000000   
mean   4.855407e+09   7637.910638       5.489702         5.475351   
std    2.424805e+09   5087.150742       3.924606         3.907276   
min    1.503960e+09      0.000000       0.000000         0.000000   
25%    2.320127e+09   3789.750000       2.620000         2.620000   
50%    4.445115e+09   7405.500000       5.245000         5.245000   
75%    6.962181e+09  10727.000000       7.712500         7.710000   
max    8.877689e+09  36019.000000      28.030001        28.030001   

       LoggedActivitiesDistance  VeryActiveDistance  ModeratelyActiveDistance  \
count                940.000000          940.000000                940.000000   
mean                   0.108171            1.502681                  0.567543   
std                    0.619897            2.658941                  0.883580   
min                    0.000000            0.000000                  0.000000   
25%                    0.000000            0.000000                  0.000000   
50%                    0.000000            0.210000                  0.240000   
75%                    0.000000            2.052500                  0.800000   
max                    4.942142           21.920000                  6.480000   

       LightActiveDistance  SedentaryActiveDistance  VeryActiveMinutes  \
count           940.000000               940.000000         940.000000   
mean              3.340819                 0.001606          21.164894   
std               2.040655                 0.007346          32.844803   
min               0.000000                 0.000000           0.000000   
25%               1.945000                 0.000000           0.000000   
50%               3.365000                 0.000000           4.000000   
75%               4.782500                 0.000000          32.000000   
max              10.710000                 0.110000         210.000000   

       FairlyActiveMinutes  LightlyActiveMinutes  SedentaryMinutes  \
count           940.000000            940.000000        940.000000   
mean             13.564894            192.812766        991.210638   
std              19.987404            109.174700        301.267437   
min               0.000000              0.000000          0.000000   
25%               0.000000            127.000000        729.750000   
50%               6.000000            199.000000       1057.500000   
75%              19.000000            264.000000       1229.500000   
max             143.000000            518.000000       1440.000000   

          Calories  
count   940.000000  
mean   2303.609574  
std     718.166862  
min       0.000000  
25%    1828.500000  
50%    2134.000000  
75%    2793.250000  
max    4900.000000

In [5]:
pstr(dailyCalories_merged)

C:\Users\User\AppData\Local\Temp\ipykernel_14676\3310633354.py:4: FutureWarning: null_counts is deprecated. Use show_counts instead
  print(df.info(null_counts=True, verbose=True))


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 940 entries, 0 to 939
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Id           940 non-null    int64 
 1   ActivityDay  940 non-null    object
 2   Calories     940 non-null    int64 
dtypes: int64(2), object(1)
memory usage: 22.2+ KB
None


0
Id           [1503960366, 1624580081, 1644430081, 184450507...
ActivityDay  [4/12/2016, 4/13/2016, 4/14/2016, 4/15/2016, 4...
Calories                        [1985, 1797, 1776, 1745, 1863]

Id     Calories
count  9.400000e+02   940.000000
mean   4.855407e+09  2303.609574
std    2.424805e+09   718.166862
min    1.503960e+09     0.000000
25%    2.320127e+09  1828.500000
50%    4.445115e+09  2134.000000
75%    6.962181e+09  2793.250000
max    8.877689e+09  4900.000000

In [6]:
pstr(dailyIntensities_merged)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 940 entries, 0 to 939
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Id                        940 non-null    int64  
 1   ActivityDay               940 non-null    object 
 2   SedentaryMinutes          940 non-null    int64  
 3   LightlyActiveMinutes      940 non-null    int64  
 4   FairlyActiveMinutes       940 non-null    int64  
 5   VeryActiveMinutes         940 non-null    int64  
 6   SedentaryActiveDistance   940 non-null    float64
 7   LightActiveDistance       940 non-null    float64
 8   ModeratelyActiveDistance  940 non-null    float64
 9   VeryActiveDistance        940 non-null    float64
dtypes: float64(4), int64(5), object(1)
memory usage: 73.6+ KB
None


C:\Users\User\AppData\Local\Temp\ipykernel_14676\3310633354.py:4: FutureWarning: null_counts is deprecated. Use show_counts instead
  print(df.info(null_counts=True, verbose=True))


0
Id                        [1503960366, 1624580081, 1644430081, 184450507...
ActivityDay               [4/12/2016, 4/13/2016, 4/14/2016, 4/15/2016, 4...
SedentaryMinutes                                 [728, 776, 1218, 726, 773]
LightlyActiveMinutes                              [328, 217, 181, 209, 221]
FairlyActiveMinutes                                    [13, 19, 11, 34, 10]
VeryActiveMinutes                                      [25, 21, 30, 29, 36]
SedentaryActiveDistance   [0.0, 0.0099999997764825, 0.0199999995529652, ...
LightActiveDistance       [6.05999994277954, 4.71000003814697, 3.9100000...
ModeratelyActiveDistance  [0.550000011920929, 0.689999997615814, 0.40000...
VeryActiveDistance        [1.87999999523163, 1.57000005245209, 2.4400000...

Id  SedentaryMinutes  LightlyActiveMinutes  \
count  9.400000e+02        940.000000            940.000000   
mean   4.855407e+09        991.210638            192.812766   
std    2.424805e+09        301.267437            109.174700   
min    1.503960e+09          0.000000              0.000000   
25%    2.320127e+09        729.750000            127.000000   
50%    4.445115e+09       1057.500000            199.000000   
75%    6.962181e+09       1229.500000            264.000000   
max    8.877689e+09       1440.000000            518.000000   

       FairlyActiveMinutes  VeryActiveMinutes  SedentaryActiveDistance  \
count           940.000000         940.000000               940.000000   
mean             13.564894          21.164894                 0.001606   
std              19.987404          32.844803                 0.007346   
min               0.000000           0.000000                 0.000000   
25%               0.000000           0.000000                 0.000000   
50%               6.000000           4.000000                 0.000000   
75%              19.000000          32.000000                 0.000000   
max             143.000000         210.000000                 0.110000   

       LightActiveDistance  ModeratelyActiveDistance  VeryActiveDistance  
count           940.000000                940.000000          940.000000  
mean              3.340819                  0.567543            1.502681  
std               2.040655                  0.883580            2.658941  
min               0.000000                  0.000000            0.000000  
25%               1.945000                  0.000000            0.000000  
50%               3.365000                  0.240000            0.210000  
75%               4.782500                  0.800000            2.052500  
max              10.710000                  6.480000           21.920000

In [7]:
pstr(dailySteps_merged)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 940 entries, 0 to 939
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Id           940 non-null    int64 
 1   ActivityDay  940 non-null    object
 2   StepTotal    940 non-null    int64 
dtypes: int64(2), object(1)
memory usage: 22.2+ KB
None


C:\Users\User\AppData\Local\Temp\ipykernel_14676\3310633354.py:4: FutureWarning: null_counts is deprecated. Use show_counts instead
  print(df.info(null_counts=True, verbose=True))


0
Id           [1503960366, 1624580081, 1644430081, 184450507...
ActivityDay  [4/12/2016, 4/13/2016, 4/14/2016, 4/15/2016, 4...
StepTotal                   [13162, 10735, 10460, 9762, 12669]

Id     StepTotal
count  9.400000e+02    940.000000
mean   4.855407e+09   7637.910638
std    2.424805e+09   5087.150742
min    1.503960e+09      0.000000
25%    2.320127e+09   3789.750000
50%    4.445115e+09   7405.500000
75%    6.962181e+09  10727.000000
max    8.877689e+09  36019.000000

In [8]:
pstr(heartrate_seconds_merged)

C:\Users\User\AppData\Local\Temp\ipykernel_14676\3310633354.py:4: FutureWarning: null_counts is deprecated. Use show_counts instead
  print(df.info(null_counts=True, verbose=True))


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2483658 entries, 0 to 2483657
Data columns (total 3 columns):
 #   Column  Non-Null Count    Dtype 
---  ------  --------------    ----- 
 0   Id      2483658 non-null  int64 
 1   Time    2483658 non-null  object
 2   Value   2483658 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 56.8+ MB
None


0
Id     [2022484408, 2026352035, 2347167796, 402033265...
Time   [4/12/2016 7:21:00 AM, 4/12/2016 7:21:05 AM, 4...
Value                           [97, 102, 105, 103, 101]

Id         Value
count  2.483658e+06  2.483658e+06
mean   5.513765e+09  7.732842e+01
std    1.950224e+09  1.940450e+01
min    2.022484e+09  3.600000e+01
25%    4.388162e+09  6.300000e+01
50%    5.553957e+09  7.300000e+01
75%    6.962181e+09  8.800000e+01
max    8.877689e+09  2.030000e+02

In [9]:
pstr(hourlyCalories_merged)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22099 entries, 0 to 22098
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Id            22099 non-null  int64 
 1   ActivityHour  22099 non-null  object
 2   Calories      22099 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 518.1+ KB
None


C:\Users\User\AppData\Local\Temp\ipykernel_14676\3310633354.py:4: FutureWarning: null_counts is deprecated. Use show_counts instead
  print(df.info(null_counts=True, verbose=True))


0
Id            [1503960366, 1624580081, 1644430081, 184450507...
ActivityHour  [4/12/2016 12:00:00 AM, 4/12/2016 1:00:00 AM, ...
Calories                                   [81, 61, 59, 47, 48]

Id      Calories
count  2.209900e+04  22099.000000
mean   4.848235e+09     97.386760
std    2.422500e+09     60.702622
min    1.503960e+09     42.000000
25%    2.320127e+09     63.000000
50%    4.445115e+09     83.000000
75%    6.962181e+09    108.000000
max    8.877689e+09    948.000000

In [10]:
pstr(hourlyIntensities_merged)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22099 entries, 0 to 22098
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Id                22099 non-null  int64  
 1   ActivityHour      22099 non-null  object 
 2   TotalIntensity    22099 non-null  int64  
 3   AverageIntensity  22099 non-null  float64
dtypes: float64(1), int64(2), object(1)
memory usage: 690.7+ KB
None


C:\Users\User\AppData\Local\Temp\ipykernel_14676\3310633354.py:4: FutureWarning: null_counts is deprecated. Use show_counts instead
  print(df.info(null_counts=True, verbose=True))


0
Id                [1503960366, 1624580081, 1644430081, 184450507...
ActivityHour      [4/12/2016 12:00:00 AM, 4/12/2016 1:00:00 AM, ...
TotalIntensity                                    [20, 8, 7, 0, 13]
AverageIntensity      [0.333333, 0.133333, 0.116667, 0.0, 0.216667]

Id  TotalIntensity  AverageIntensity
count  2.209900e+04    22099.000000      22099.000000
mean   4.848235e+09       12.035341          0.200589
std    2.422500e+09       21.133110          0.352219
min    1.503960e+09        0.000000          0.000000
25%    2.320127e+09        0.000000          0.000000
50%    4.445115e+09        3.000000          0.050000
75%    6.962181e+09       16.000000          0.266667
max    8.877689e+09      180.000000          3.000000

In [11]:
pstr(hourlySteps_merged)

C:\Users\User\AppData\Local\Temp\ipykernel_14676\3310633354.py:4: FutureWarning: null_counts is deprecated. Use show_counts instead
  print(df.info(null_counts=True, verbose=True))


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22099 entries, 0 to 22098
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Id            22099 non-null  int64 
 1   ActivityHour  22099 non-null  object
 2   StepTotal     22099 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 518.1+ KB
None


0
Id            [1503960366, 1624580081, 1644430081, 184450507...
ActivityHour  [4/12/2016 12:00:00 AM, 4/12/2016 1:00:00 AM, ...
StepTotal                               [373, 160, 151, 0, 250]

Id     StepTotal
count  2.209900e+04  22099.000000
mean   4.848235e+09    320.166342
std    2.422500e+09    690.384228
min    1.503960e+09      0.000000
25%    2.320127e+09      0.000000
50%    4.445115e+09     40.000000
75%    6.962181e+09    357.000000
max    8.877689e+09  10554.000000

In [12]:
pstr(minuteCaloriesNarrow_merged)

C:\Users\User\AppData\Local\Temp\ipykernel_14676\3310633354.py:4: FutureWarning: null_counts is deprecated. Use show_counts instead
  print(df.info(null_counts=True, verbose=True))


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1325580 entries, 0 to 1325579
Data columns (total 3 columns):
 #   Column          Non-Null Count    Dtype  
---  ------          --------------    -----  
 0   Id              1325580 non-null  int64  
 1   ActivityMinute  1325580 non-null  object 
 2   Calories        1325580 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 30.3+ MB
None


0
Id              [1503960366, 1624580081, 1644430081, 184450507...
ActivityMinute  [4/12/2016 12:00:00 AM, 4/12/2016 12:01:00 AM,...
Calories        [0.786499977111816, 0.94379997253418, 2.044899...

Id      Calories
count  1.325580e+06  1.325580e+06
mean   4.847898e+09  1.623130e+00
std    2.422313e+09  1.410447e+00
min    1.503960e+09  0.000000e+00
25%    2.320127e+09  9.357000e-01
50%    4.445115e+09  1.217600e+00
75%    6.962181e+09  1.432700e+00
max    8.877689e+09  1.974995e+01

In [13]:
pstr(minuteCaloriesWide_merged)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21645 entries, 0 to 21644
Data columns (total 62 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Id            21645 non-null  int64  
 1   ActivityHour  21645 non-null  object 
 2   Calories00    21645 non-null  float64
 3   Calories01    21645 non-null  float64
 4   Calories02    21645 non-null  float64
 5   Calories03    21645 non-null  float64
 6   Calories04    21645 non-null  float64
 7   Calories05    21645 non-null  float64
 8   Calories06    21645 non-null  float64
 9   Calories07    21645 non-null  float64
 10  Calories08    21645 non-null  float64
 11  Calories09    21645 non-null  float64
 12  Calories10    21645 non-null  float64
 13  Calories11    21645 non-null  float64
 14  Calories12    21645 non-null  float64
 15  Calories13    21645 non-null  float64
 16  Calories14    21645 non-null  float64
 17  Calories15    21645 non-null  float64
 18  Calories16    21645 non-nu

C:\Users\User\AppData\Local\Temp\ipykernel_14676\3310633354.py:4: FutureWarning: null_counts is deprecated. Use show_counts instead
  print(df.info(null_counts=True, verbose=True))


0
Id            [1503960366, 1624580081, 1644430081, 184450507...
ActivityHour  [4/13/2016 12:00:00 AM, 4/13/2016 1:00:00 AM, ...
Calories00    [1.88759994506836, 0.786499977111816, 0.943799...
Calories01    [2.20219993591309, 0.786499977111816, 2.044899...
Calories02    [0.94379997253418, 0.786499977111816, 2.044899...
...                                                         ...
Calories55    [1.88759994506836, 0.786499977111816, 0.943799...
Calories56    [0.94379997253418, 0.786499977111816, 2.516799...
Calories57    [0.94379997253418, 0.786499977111816, 2.044899...
Calories58    [0.94379997253418, 0.786499977111816, 2.831399...
Calories59    [0.94379997253418, 0.786499977111816, 2.202199...

[62 rows x 1 columns]

Id    Calories00    Calories01    Calories02    Calories03  \
count  2.164500e+04  21645.000000  21645.000000  21645.000000  21645.000000   
mean   4.836965e+09      1.622629      1.626377      1.637824      1.635515   
std    2.424088e+09      1.398418      1.395083      1.408828      1.419590   
min    1.503960e+09      0.702700      0.702700      0.702700      0.702700   
25%    2.320127e+09      0.935700      0.935700      0.937680      0.935700   
50%    4.445115e+09      1.217600      1.217600      1.220400      1.218500   
75%    6.962181e+09      1.432700      1.432700      1.432700      1.432700   
max    8.877689e+09     19.727337     19.727337     19.727337     19.727337   

         Calories04    Calories05    Calories06    Calories07    Calories08  \
count  21645.000000  21645.000000  21645.000000  21645.000000  21645.000000   
mean       1.637997      1.638306      1.639910      1.629520      1.623686   
std        1.433532      1.438253      1.435465      1.424092      1.411596   
min        0.702700      0.702700      0.702700      0.702700      0.702700   
25%        0.935700      0.935700      0.935700      0.935700      0.935700   
50%        1.218500      1.218500      1.218500      1.217600      1.217600   
75%        1.432700      1.432700      1.432700      1.432700      1.432700   
max       19.727337     19.727337     19.727337     19.727337     19.727337   

       ...    Calories50    Calories51    Calories52    Calories53  \
count  ...  21645.000000  21645.000000  21645.000000  21645.000000   
mean   ...      1.623665      1.613643      1.620958      1.618227   
std    ...      1.407171      1.395206      1.407914      1.400498   
min    ...      0.702700      0.702700      0.702700      0.702700   
25%    ...      0.935700      0.935700      0.935700      0.935700   
50%    ...      1.217600      1.217600      1.217600      1.217600   
75%    ...      1.432700      1.432700      1.432700      1.432700   
max    ...     19.749947     19.749947     19.749947     19.749947   

         Calories54    Calories55    Calories56    Calories57    Calories58  \
count  21645.000000  21645.000000  21645.000000  21645.000000  21645.000000   
mean       1.621229      1.615972      1.608714      1.612657      1.611715   
std        1.408974      1.392530      1.376827      1.369097      1.374954   
min        0.702700      0.702700      0.702700      0.702700      0.702700   
25%        0.935700      0.935700      0.935700      0.935700      0.935700   
50%        1.217600      1.217600      1.217600      1.217600      1.217600   
75%        1.432700      1.432700      1.432700      1.432700      1.432700   
max       19.749947     19.749947     19.727337     19.727337     19.727337   

         Calories59  
count  21645.000000  
mean       1.612110  
std        1.373888  
min        0.000000  
25%        0.935700  
50%        1.217600  
75%        1.432700  
max       19.727337  

[8 rows x 61 columns]

In [14]:
pstr(minuteIntensitiesNarrow_merged)

C:\Users\User\AppData\Local\Temp\ipykernel_14676\3310633354.py:4: FutureWarning: null_counts is deprecated. Use show_counts instead
  print(df.info(null_counts=True, verbose=True))


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1325580 entries, 0 to 1325579
Data columns (total 3 columns):
 #   Column          Non-Null Count    Dtype 
---  ------          --------------    ----- 
 0   Id              1325580 non-null  int64 
 1   ActivityMinute  1325580 non-null  object
 2   Intensity       1325580 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 30.3+ MB
None


0
Id              [1503960366, 1624580081, 1644430081, 184450507...
ActivityMinute  [4/12/2016 12:00:00 AM, 4/12/2016 12:01:00 AM,...
Intensity                                            [0, 1, 2, 3]

Id     Intensity
count  1.325580e+06  1.325580e+06
mean   4.847898e+09  2.005937e-01
std    2.422313e+09  5.190227e-01
min    1.503960e+09  0.000000e+00
25%    2.320127e+09  0.000000e+00
50%    4.445115e+09  0.000000e+00
75%    6.962181e+09  0.000000e+00
max    8.877689e+09  3.000000e+00

In [15]:
pstr(minuteIntensitiesWide_merged)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21645 entries, 0 to 21644
Data columns (total 62 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Id            21645 non-null  int64 
 1   ActivityHour  21645 non-null  object
 2   Intensity00   21645 non-null  int64 
 3   Intensity01   21645 non-null  int64 
 4   Intensity02   21645 non-null  int64 
 5   Intensity03   21645 non-null  int64 
 6   Intensity04   21645 non-null  int64 
 7   Intensity05   21645 non-null  int64 
 8   Intensity06   21645 non-null  int64 
 9   Intensity07   21645 non-null  int64 
 10  Intensity08   21645 non-null  int64 
 11  Intensity09   21645 non-null  int64 
 12  Intensity10   21645 non-null  int64 
 13  Intensity11   21645 non-null  int64 
 14  Intensity12   21645 non-null  int64 
 15  Intensity13   21645 non-null  int64 
 16  Intensity14   21645 non-null  int64 
 17  Intensity15   21645 non-null  int64 
 18  Intensity16   21645 non-null  int64 
 19  Inte

C:\Users\User\AppData\Local\Temp\ipykernel_14676\3310633354.py:4: FutureWarning: null_counts is deprecated. Use show_counts instead
  print(df.info(null_counts=True, verbose=True))


0
Id            [1503960366, 1624580081, 1644430081, 184450507...
ActivityHour  [4/13/2016 12:00:00 AM, 4/13/2016 1:00:00 AM, ...
Intensity00                                        [1, 0, 3, 2]
Intensity01                                        [1, 0, 3, 2]
Intensity02                                        [0, 1, 3, 2]
...                                                         ...
Intensity55                                        [1, 0, 2, 3]
Intensity56                                        [0, 1, 2, 3]
Intensity57                                        [0, 1, 3, 2]
Intensity58                                        [0, 1, 3, 2]
Intensity59                                        [0, 1, 3, 2]

[62 rows x 1 columns]

Id   Intensity00   Intensity01   Intensity02   Intensity03  \
count  2.164500e+04  21645.000000  21645.000000  21645.000000  21645.000000   
mean   4.836965e+09      0.199723      0.203326      0.208177      0.203835   
std    2.424088e+09      0.509819      0.515432      0.521394      0.518137   
min    1.503960e+09      0.000000      0.000000      0.000000      0.000000   
25%    2.320127e+09      0.000000      0.000000      0.000000      0.000000   
50%    4.445115e+09      0.000000      0.000000      0.000000      0.000000   
75%    6.962181e+09      0.000000      0.000000      0.000000      0.000000   
max    8.877689e+09      3.000000      3.000000      3.000000      3.000000   

        Intensity04   Intensity05   Intensity06   Intensity07   Intensity08  \
count  21645.000000  21645.000000  21645.000000  21645.000000  21645.000000   
mean       0.205082      0.204897      0.206560      0.201894      0.202310   
std        0.521956      0.521054      0.523053      0.519074      0.522594   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      0.000000      0.000000      0.000000      0.000000   
max        3.000000      3.000000      3.000000      3.000000      3.000000   

       ...   Intensity50   Intensity51   Intensity52   Intensity53  \
count  ...  21645.000000  21645.000000  21645.000000  21645.000000   
mean   ...      0.201016      0.195796      0.198337      0.199399   
std    ...      0.514814      0.510299      0.511264      0.513331   
min    ...      0.000000      0.000000      0.000000      0.000000   
25%    ...      0.000000      0.000000      0.000000      0.000000   
50%    ...      0.000000      0.000000      0.000000      0.000000   
75%    ...      0.000000      0.000000      0.000000      0.000000   
max    ...      3.000000      3.000000      3.000000      3.000000   

        Intensity54   Intensity55   Intensity56   Intensity57   Intensity58  \
count  21645.000000  21645.000000  21645.000000  21645.000000  21645.000000   
mean       0.200139      0.198753      0.195565      0.199122      0.198244   
std        0.512142      0.511238      0.506435      0.511907      0.510124   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      0.000000      0.000000      0.000000      0.000000   
max        3.000000      3.000000      3.000000      3.000000      3.000000   

        Intensity59  
count  21645.000000  
mean       0.195426  
std        0.503423  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        0.000000  
max        3.000000  

[8 rows x 61 columns]

In [16]:
pstr(minuteMETsNarrow_merged)

C:\Users\User\AppData\Local\Temp\ipykernel_14676\3310633354.py:4: FutureWarning: null_counts is deprecated. Use show_counts instead
  print(df.info(null_counts=True, verbose=True))


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1325580 entries, 0 to 1325579
Data columns (total 3 columns):
 #   Column          Non-Null Count    Dtype 
---  ------          --------------    ----- 
 0   Id              1325580 non-null  int64 
 1   ActivityMinute  1325580 non-null  object
 2   METs            1325580 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 30.3+ MB
None


0
Id              [1503960366, 1624580081, 1644430081, 184450507...
ActivityMinute  [4/12/2016 12:00:00 AM, 4/12/2016 12:01:00 AM,...
METs                                         [10, 12, 26, 32, 36]

Id          METs
count  1.325580e+06  1.325580e+06
mean   4.847898e+09  1.469001e+01
std    2.422313e+09  1.205541e+01
min    1.503960e+09  0.000000e+00
25%    2.320127e+09  1.000000e+01
50%    4.445115e+09  1.000000e+01
75%    6.962181e+09  1.100000e+01
max    8.877689e+09  1.570000e+02

In [17]:
pstr(minuteSleep_merged)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188521 entries, 0 to 188520
Data columns (total 4 columns):
 #   Column  Non-Null Count   Dtype 
---  ------  --------------   ----- 
 0   Id      188521 non-null  int64 
 1   date    188521 non-null  object
 2   value   188521 non-null  int64 
 3   logId   188521 non-null  int64 
dtypes: int64(3), object(1)
memory usage: 5.8+ MB
None


C:\Users\User\AppData\Local\Temp\ipykernel_14676\3310633354.py:4: FutureWarning: null_counts is deprecated. Use show_counts instead
  print(df.info(null_counts=True, verbose=True))


0
Id     [1503960366, 1644430081, 1844505072, 192797227...
date   [4/12/2016 2:47:30 AM, 4/12/2016 2:48:30 AM, 4...
value                                          [3, 2, 1]
logId  [11380564589, 11388770715, 11388770716, 114027...

Id          value         logId
count  1.885210e+05  188521.000000  1.885210e+05
mean   4.996595e+09       1.095793  1.149611e+10
std    2.066950e+09       0.328673  6.822863e+07
min    1.503960e+09       1.000000  1.137223e+10
25%    3.977334e+09       1.000000  1.143931e+10
50%    4.702922e+09       1.000000  1.150114e+10
75%    6.962181e+09       1.000000  1.155253e+10
max    8.792010e+09       3.000000  1.161625e+10

In [18]:
pstr(minuteStepsNarrow_merged)

C:\Users\User\AppData\Local\Temp\ipykernel_14676\3310633354.py:4: FutureWarning: null_counts is deprecated. Use show_counts instead
  print(df.info(null_counts=True, verbose=True))


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1325580 entries, 0 to 1325579
Data columns (total 3 columns):
 #   Column          Non-Null Count    Dtype 
---  ------          --------------    ----- 
 0   Id              1325580 non-null  int64 
 1   ActivityMinute  1325580 non-null  object
 2   Steps           1325580 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 30.3+ MB
None


0
Id              [1503960366, 1624580081, 1644430081, 184450507...
ActivityMinute  [4/12/2016 12:00:00 AM, 4/12/2016 12:01:00 AM,...
Steps                                          [0, 7, 32, 41, 29]

Id         Steps
count  1.325580e+06  1.325580e+06
mean   4.847898e+09  5.336192e+00
std    2.422313e+09  1.812830e+01
min    1.503960e+09  0.000000e+00
25%    2.320127e+09  0.000000e+00
50%    4.445115e+09  0.000000e+00
75%    6.962181e+09  0.000000e+00
max    8.877689e+09  2.200000e+02

In [19]:
pstr(minuteStepsWide_merged)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21645 entries, 0 to 21644
Data columns (total 62 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Id            21645 non-null  int64 
 1   ActivityHour  21645 non-null  object
 2   Steps00       21645 non-null  int64 
 3   Steps01       21645 non-null  int64 
 4   Steps02       21645 non-null  int64 
 5   Steps03       21645 non-null  int64 
 6   Steps04       21645 non-null  int64 
 7   Steps05       21645 non-null  int64 
 8   Steps06       21645 non-null  int64 
 9   Steps07       21645 non-null  int64 
 10  Steps08       21645 non-null  int64 
 11  Steps09       21645 non-null  int64 
 12  Steps10       21645 non-null  int64 
 13  Steps11       21645 non-null  int64 
 14  Steps12       21645 non-null  int64 
 15  Steps13       21645 non-null  int64 
 16  Steps14       21645 non-null  int64 
 17  Steps15       21645 non-null  int64 
 18  Steps16       21645 non-null  int64 
 19  Step

C:\Users\User\AppData\Local\Temp\ipykernel_14676\3310633354.py:4: FutureWarning: null_counts is deprecated. Use show_counts instead
  print(df.info(null_counts=True, verbose=True))


0
Id            [1503960366, 1624580081, 1644430081, 184450507...
ActivityHour  [4/13/2016 12:00:00 AM, 4/13/2016 1:00:00 AM, ...
Steps00                                       [4, 0, 37, 9, 91]
Steps01                                     [16, 0, 14, 11, 30]
Steps02                                      [0, 10, 30, 64, 6]
...                                                         ...
Steps55                                       [1, 0, 84, 7, 81]
Steps56                                      [0, 31, 5, 47, 27]
Steps57                                    [0, 11, 115, 14, 29]
Steps58                                   [0, 42, 105, 11, 130]
Steps59                                     [0, 16, 2, 105, 12]

[62 rows x 1 columns]

Id       Steps00       Steps01       Steps02       Steps03  \
count  2.164500e+04  21645.000000  21645.000000  21645.000000  21645.000000   
mean   4.836965e+09      5.304366      5.335412      5.531439      5.469439   
std    2.424088e+09     17.783331     17.678358     18.079791     18.106414   
min    1.503960e+09      0.000000      0.000000      0.000000      0.000000   
25%    2.320127e+09      0.000000      0.000000      0.000000      0.000000   
50%    4.445115e+09      0.000000      0.000000      0.000000      0.000000   
75%    6.962181e+09      0.000000      0.000000      0.000000      0.000000   
max    8.877689e+09    186.000000    180.000000    182.000000    182.000000   

            Steps04       Steps05       Steps06       Steps07      Steps08  \
count  21645.000000  21645.000000  21645.000000  21645.000000  21645.00000   
mean       5.461862      5.590252      5.559483      5.412474      5.35879   
std       18.288469     18.565165     18.484912     18.335665     18.20523   
min        0.000000      0.000000      0.000000      0.000000      0.00000   
25%        0.000000      0.000000      0.000000      0.000000      0.00000   
50%        0.000000      0.000000      0.000000      0.000000      0.00000   
75%        0.000000      0.000000      0.000000      0.000000      0.00000   
max      181.000000    180.000000    181.000000    183.000000    180.00000   

       ...       Steps50       Steps51       Steps52       Steps53  \
count  ...  21645.000000  21645.000000  21645.000000  21645.000000   
mean   ...      5.329175      5.194456      5.225595      5.145484   
std    ...     17.870527     17.601857     17.618497     17.570195   
min    ...      0.000000      0.000000      0.000000      0.000000   
25%    ...      0.000000      0.000000      0.000000      0.000000   
50%    ...      0.000000      0.000000      0.000000      0.000000   
75%    ...      0.000000      0.000000      0.000000      0.000000   
max    ...    182.000000    181.000000    181.000000    181.000000   

            Steps54       Steps55       Steps56       Steps57       Steps58  \
count  21645.000000  21645.000000  21645.000000  21645.000000  21645.000000   
mean       5.223654      5.281220      5.179533      5.251836      5.143636   
std       17.684634     17.828413     17.569268     17.686583     17.427494   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      0.000000      0.000000      0.000000      0.000000   
max      184.000000    181.000000    182.000000    182.000000    180.000000   

            Steps59  
count  21645.000000  
mean       5.288935  
std       17.721454  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        0.000000  
max      189.000000  

[8 rows x 61 columns]

In [20]:
print(sleepDay_merged.info(null_counts=True, verbose=True))
display(sleepDay_merged.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 413 entries, 0 to 412
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   Id                  413 non-null    int64 
 1   SleepDay            413 non-null    object
 2   TotalSleepRecords   413 non-null    int64 
 3   TotalMinutesAsleep  413 non-null    int64 
 4   TotalTimeInBed      413 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 16.3+ KB
None


C:\Users\User\AppData\Local\Temp\ipykernel_14676\2059558041.py:1: FutureWarning: null_counts is deprecated. Use show_counts instead
  print(sleepDay_merged.info(null_counts=True, verbose=True))


Id  TotalSleepRecords  TotalMinutesAsleep  TotalTimeInBed
count  4.130000e+02         413.000000          413.000000      413.000000
mean   5.000979e+09           1.118644          419.467312      458.639225
std    2.060360e+09           0.345521          118.344679      127.101607
min    1.503960e+09           1.000000           58.000000       61.000000
25%    3.977334e+09           1.000000          361.000000      403.000000
50%    4.702922e+09           1.000000          433.000000      463.000000
75%    6.962181e+09           1.000000          490.000000      526.000000
max    8.792010e+09           3.000000          796.000000      961.000000

In [21]:
pstr(weightLogInfo_merged)

C:\Users\User\AppData\Local\Temp\ipykernel_14676\3310633354.py:4: FutureWarning: null_counts is deprecated. Use show_counts instead
  print(df.info(null_counts=True, verbose=True))


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Id              67 non-null     int64  
 1   Date            67 non-null     object 
 2   WeightKg        67 non-null     float64
 3   WeightPounds    67 non-null     float64
 4   Fat             2 non-null      float64
 5   BMI             67 non-null     float64
 6   IsManualReport  67 non-null     bool   
 7   LogId           67 non-null     int64  
dtypes: bool(1), float64(4), int64(2), object(1)
memory usage: 3.9+ KB
None


0
Id              [1503960366, 1927972279, 2873212765, 431970357...
Date            [5/2/2016 11:59:59 PM, 5/3/2016 11:59:59 PM, 4...
WeightKg        [52.5999984741211, 133.5, 56.7000007629395, 57...
WeightPounds    [115.963146545323, 294.317120016975, 125.00210...
Fat                                             [22.0, nan, 25.0]
BMI             [22.6499996185303, 47.5400009155273, 21.450000...
IsManualReport                                      [True, False]
LogId           [1462233599000, 1462319999000, 1460509732000, ...

Id    WeightKg  WeightPounds       Fat        BMI  \
count  6.700000e+01   67.000000     67.000000   2.00000  67.000000   
mean   7.009282e+09   72.035821    158.811801  23.50000  25.185224   
std    1.950322e+09   13.923206     30.695415   2.12132   3.066963   
min    1.503960e+09   52.599998    115.963147  22.00000  21.450001   
25%    6.962181e+09   61.400002    135.363832  22.75000  23.959999   
50%    6.962181e+09   62.500000    137.788914  23.50000  24.389999   
75%    8.877689e+09   85.049999    187.503152  24.25000  25.559999   
max    8.877689e+09  133.500000    294.317120  25.00000  47.540001   

              LogId  
count  6.700000e+01  
mean   1.461772e+12  
std    7.829948e+08  
min    1.460444e+12  
25%    1.461079e+12  
50%    1.461802e+12  
75%    1.462375e+12  
max    1.463098e+12

#### Clean the data


In [22]:
# Change the Id column to string
dailyActivity_merged['Id'] = dailyActivity_merged['Id'].astype(str)
dailyCalories_merged['Id'] = dailyCalories_merged['Id'].astype(str)
dailyIntensities_merged['Id'] = dailyIntensities_merged['Id'].astype(str)
dailySteps_merged['Id'] = dailySteps_merged['Id'].astype(str)
heartrate_seconds_merged['Id'] = heartrate_seconds_merged['Id'].astype(str)
hourlyCalories_merged['Id'] = hourlyCalories_merged['Id'].astype(str)
hourlyIntensities_merged['Id'] = hourlyIntensities_merged['Id'].astype(str)
hourlySteps_merged['Id'] = hourlySteps_merged['Id'].astype(str)
minuteCaloriesNarrow_merged['Id'] = minuteCaloriesNarrow_merged['Id'].astype(str)
minuteCaloriesWide_merged['Id'] = minuteCaloriesWide_merged['Id'].astype(str)
minuteIntensitiesNarrow_merged['Id'] = minuteIntensitiesNarrow_merged['Id'].astype(str)
minuteIntensitiesWide_merged['Id'] = minuteIntensitiesWide_merged['Id'].astype(str)
minuteMETsNarrow_merged['Id'] = minuteMETsNarrow_merged['Id'].astype(str)
minuteSleep_merged['Id'] = minuteSleep_merged['Id'].astype(str)
minuteStepsNarrow_merged['Id'] = minuteStepsNarrow_merged['Id'].astype(str)
minuteStepsWide_merged['Id'] = minuteStepsWide_merged['Id'].astype(str)
sleepDay_merged['Id'] = sleepDay_merged['Id'].astype(str)
weightLogInfo_merged['Id'] = weightLogInfo_merged['Id'].astype(str)


# Change the date and time format from string
format_second_p = '%m/%d/%Y %I:%M:%S %p'
format_mdy = '%m/%d/%Y'

dailyActivity_merged['ActivityDate'] = [datetime.strptime(x, format_mdy) for x in dailyActivity_merged['ActivityDate'].values]
dailyActivity_merged.rename(columns={'ActivityDate':'date'}, inplace=True)
dailyCalories_merged['ActivityDay'] = [datetime.strptime(x, format_mdy) for x in dailyCalories_merged['ActivityDay'].values]
dailyCalories_merged.rename(columns={'ActivityDay':'date'}, inplace=True)
dailyIntensities_merged['ActivityDay'] = [datetime.strptime(x, format_mdy) for x in dailyIntensities_merged['ActivityDay'].values]
dailyIntensities_merged.rename(columns={'ActivityDay':'date'}, inplace=True)
dailySteps_merged['ActivityDay'] = [datetime.strptime(x, format_mdy) for x in dailySteps_merged['ActivityDay'].values]
dailySteps_merged.rename(columns={'ActivityDay':'date'}, inplace=True)

hourlyCalories_merged['ActivityHour'] = [datetime.strptime(x, format_second_p) for x in hourlyCalories_merged['ActivityHour'].values]
hourlyCalories_merged.rename(columns={'ActivityHour':'datetime'}, inplace=True)
hourlyIntensities_merged['ActivityHour'] = [datetime.strptime(x, format_second_p) for x in hourlyIntensities_merged['ActivityHour'].values]
hourlyIntensities_merged.rename(columns={'ActivityHour':'datetime'}, inplace=True)
hourlySteps_merged['ActivityHour'] = [datetime.strptime(x, format_second_p) for x in hourlySteps_merged['ActivityHour'].values]
hourlySteps_merged.rename(columns={'ActivityHour':'datetime'}, inplace=True)

minuteCaloriesNarrow_merged['ActivityMinute'] = [datetime.strptime(x, format_second_p) for x in minuteCaloriesNarrow_merged['ActivityMinute'].values]
minuteCaloriesNarrow_merged.rename(columns={'ActivityMinute':'datetime'}, inplace=True)
minuteCaloriesWide_merged['ActivityHour'] = [datetime.strptime(x, format_second_p) for x in minuteCaloriesWide_merged['ActivityHour'].values]
minuteCaloriesWide_merged.rename(columns={'ActivityHour':'datetime'}, inplace=True)
minuteIntensitiesNarrow_merged['ActivityMinute'] = [datetime.strptime(x, format_second_p) for x in minuteIntensitiesNarrow_merged['ActivityMinute'].values]
minuteIntensitiesNarrow_merged.rename(columns={'ActivityMinute':'datetime'}, inplace=True)
minuteIntensitiesWide_merged['ActivityHour'] = [datetime.strptime(x, format_second_p) for x in minuteIntensitiesWide_merged['ActivityHour'].values]
minuteIntensitiesWide_merged.rename(columns={'ActivityHour':'datetime'}, inplace=True)
minuteStepsNarrow_merged['ActivityMinute'] = [datetime.strptime(x, format_second_p) for x in minuteStepsNarrow_merged['ActivityMinute'].values]
minuteStepsNarrow_merged.rename(columns={'ActivityMinute':'datetime'}, inplace=True)
minuteStepsWide_merged['ActivityHour'] = [datetime.strptime(x, format_second_p) for x in minuteStepsWide_merged['ActivityHour'].values]
minuteStepsWide_merged.rename(columns={'ActivityHour':'datetime'}, inplace=True)
sleepDay_merged['SleepDay'] = [datetime.strptime(x, format_second_p) for x in sleepDay_merged['SleepDay'].values]
sleepDay_merged.rename(columns={'SleepDay':'datetime'}, inplace=True)
weightLogInfo_merged['Date'] = [datetime.strptime(x, format_second_p) for x in weightLogInfo_merged['Date'].values]
weightLogInfo_merged.rename(columns={'Date':'datetime'}, inplace=True)


##### Merge the hourly data

In [23]:
hourly_merged = hourlySteps_merged.merge(hourlyCalories_merged, on=['Id', 'datetime'], how='outer').merge(hourlyIntensities_merged, on=['Id', 'datetime'], how='outer')
hourly_merged['Hour'] = hourly_merged.datetime.dt.hour
#Add day of week into it
hourly_merged['weekday'] = hourly_merged['datetime'].dt.day_name()

conditions = [(hourly_merged['weekday'] == 'Sunday'),
            (hourly_merged['weekday'] == 'Monday'),
            (hourly_merged['weekday'] == 'Tuesday'),
            (hourly_merged['weekday'] == 'Wednesday'),
            (hourly_merged['weekday'] == 'Thursday'),
            (hourly_merged['weekday'] == 'Friday'),
            (hourly_merged['weekday'] == 'Saturday')]

choices = [7, 1, 2, 3, 4, 5, 6]

hourly_merged['week'] = np.select(conditions, choices)
hourly_merged['week_label'] = hourly_merged['week'].astype(str) + '-' + hourly_merged['weekday']
hourly_merged['weektype'] = np.where(hourly_merged['week'] >= 6, 'WEEKEND', 'WEEKDAY')

hourly_merged

Id            datetime  StepTotal  Calories  TotalIntensity  \
0      1503960366 2016-04-12 00:00:00        373        81              20   
1      1503960366 2016-04-12 01:00:00        160        61               8   
2      1503960366 2016-04-12 02:00:00        151        59               7   
3      1503960366 2016-04-12 03:00:00          0        47               0   
4      1503960366 2016-04-12 04:00:00          0        48               0   
...           ...                 ...        ...       ...             ...   
22094  8877689391 2016-05-12 10:00:00        514       126              12   
22095  8877689391 2016-05-12 11:00:00       1407       192              29   
22096  8877689391 2016-05-12 12:00:00       3135       321              93   
22097  8877689391 2016-05-12 13:00:00        307       101               6   
22098  8877689391 2016-05-12 14:00:00        457       113               9   

       AverageIntensity  Hour   weekday  week  week_label weektype  
0              0.333333     0   Tuesday     2   2-Tuesday  WEEKDAY  
1              0.133333     1   Tuesday     2   2-Tuesday  WEEKDAY  
2              0.116667     2   Tuesday     2   2-Tuesday  WEEKDAY  
3              0.000000     3   Tuesday     2   2-Tuesday  WEEKDAY  
4              0.000000     4   Tuesday     2   2-Tuesday  WEEKDAY  
...                 ...   ...       ...   ...         ...      ...  
22094          0.200000    10  Thursday     4  4-Thursday  WEEKDAY  
22095          0.483333    11  Thursday     4  4-Thursday  WEEKDAY  
22096          1.550000    12  Thursday     4  4-Thursday  WEEKDAY  
22097          0.100000    13  Thursday     4  4-Thursday  WEEKDAY  
22098          0.150000    14  Thursday     4  4-Thursday  WEEKDAY  

[22099 rows x 11 columns]

##### Check duplicates


In [24]:
print("dailyActivity_merged # of rows (raw vs unduplicated): {:,} vs {:,}".format(dailyActivity_merged.shape[0], dailyActivity_merged.drop_duplicates().shape[0]))
print("dailyCalories_merged # of rows (raw vs unduplicated): {:,} vs {:,}".format(dailyCalories_merged.shape[0], dailyCalories_merged.drop_duplicates().shape[0]))
print("dailyIntensities_merged # of rows (raw vs unduplicated): {:,} vs {:,}".format(dailyIntensities_merged.shape[0], dailyIntensities_merged.drop_duplicates().shape[0]))
print("dailySteps_merged # of rows (raw vs unduplicated): {:,} vs {:,}".format(dailySteps_merged.shape[0], dailySteps_merged.drop_duplicates().shape[0]))
print("heartrate_seconds_merged # of rows (raw vs unduplicated): {:,} vs {:,}".format(heartrate_seconds_merged.shape[0], heartrate_seconds_merged.drop_duplicates().shape[0]))
print("hourlyCalories_merged # of rows (raw vs unduplicated): {:,} vs {:,}".format(hourlyCalories_merged.shape[0], hourlyCalories_merged.drop_duplicates().shape[0]))
print("hourlyIntensities_merged # of rows (raw vs unduplicated): {:,} vs {:,}".format(hourlyIntensities_merged.shape[0], hourlyIntensities_merged.drop_duplicates().shape[0]))
print("hourlySteps_merged # of rows (raw vs unduplicated): {:,} vs {:,}".format(hourlySteps_merged.shape[0], hourlySteps_merged.drop_duplicates().shape[0]))
print("minuteCaloriesNarrow_merged # of rows (raw vs unduplicated): {:,} vs {:,}".format(minuteCaloriesNarrow_merged.shape[0], minuteCaloriesNarrow_merged.drop_duplicates().shape[0]))
print("minuteCaloriesWide_merged # of rows (raw vs unduplicated): {:,} vs {:,}".format(minuteCaloriesWide_merged.shape[0], minuteCaloriesWide_merged.drop_duplicates().shape[0]))
print("minuteIntensitiesNarrow_merged # of rows (raw vs unduplicated): {:,} vs {:,}".format(minuteIntensitiesNarrow_merged.shape[0], minuteIntensitiesNarrow_merged.drop_duplicates().shape[0]))
print("minuteIntensitiesWide_merged # of rows (raw vs unduplicated): {:,} vs {:,}".format(minuteIntensitiesWide_merged.shape[0], minuteIntensitiesWide_merged.drop_duplicates().shape[0]))
print("minuteMETsNarrow_merged # of rows (raw vs unduplicated): {:,} vs {:,}".format(minuteMETsNarrow_merged.shape[0], minuteMETsNarrow_merged.drop_duplicates().shape[0]))
print("minuteSleep_merged # of rows (raw vs unduplicated): {:,} vs {:,}".format(minuteSleep_merged.shape[0], minuteSleep_merged.drop_duplicates().shape[0]))
print("minuteStepsNarrow_merged # of rows (raw vs unduplicated): {:,} vs {:,}".format(minuteStepsNarrow_merged.shape[0], minuteStepsNarrow_merged.drop_duplicates().shape[0]))
print("minuteStepsWide_merged # of rows (raw vs unduplicated): {:,} vs {:,}".format(minuteStepsWide_merged.shape[0], minuteStepsWide_merged.drop_duplicates().shape[0]))
print("sleepDay_merged # of rows (raw vs unduplicated): {:,} vs {:,}".format(sleepDay_merged.shape[0], sleepDay_merged.drop_duplicates().shape[0]))
print("weightLogInfo_merged # of rows (raw vs unduplicated): {:,} vs {:,}".format(weightLogInfo_merged.shape[0], weightLogInfo_merged.drop_duplicates().shape[0]))


dailyActivity_merged # of rows (raw vs unduplicated): 940 vs 940
dailyCalories_merged # of rows (raw vs unduplicated): 940 vs 940
dailyIntensities_merged # of rows (raw vs unduplicated): 940 vs 940
dailySteps_merged # of rows (raw vs unduplicated): 940 vs 940
heartrate_seconds_merged # of rows (raw vs unduplicated): 2,483,658 vs 2,483,658
hourlyCalories_merged # of rows (raw vs unduplicated): 22,099 vs 22,099
hourlyIntensities_merged # of rows (raw vs unduplicated): 22,099 vs 22,099
hourlySteps_merged # of rows (raw vs unduplicated): 22,099 vs 22,099
minuteCaloriesNarrow_merged # of rows (raw vs unduplicated): 1,325,580 vs 1,325,580
minuteCaloriesWide_merged # of rows (raw vs unduplicated): 21,645 vs 21,645
minuteIntensitiesNarrow_merged # of rows (raw vs unduplicated): 1,325,580 vs 1,325,580
minuteIntensitiesWide_merged # of rows (raw vs unduplicated): 21,645 vs 21,645
minuteMETsNarrow_merged # of rows (raw vs unduplicated): 1,325,580 vs 1,325,580
minuteSleep_merged # of rows (raw vs 

In [25]:
sleepDay_merged = sleepDay_merged.drop_duplicates()
minuteSleep_merged  = minuteSleep_merged.drop_duplicates()

There are duplicate records in the `sleep` and `minuteSleep_merged` data. The duplicates are now dropped.


### Check how many users in each data


In [26]:
dailyActivity_merged_users = dailyActivity_merged[['Id']].drop_duplicates()
dailyActivity_merged_users['dailyActivity_merged'] = 1
dailyCalories_merged_users = dailyCalories_merged[['Id']].drop_duplicates()
dailyCalories_merged_users['dailyCalories_merged'] = 1
dailyIntensities_merged_users = dailyIntensities_merged[['Id']].drop_duplicates()
dailyIntensities_merged_users['dailyIntensities_merged'] = 1
dailySteps_merged_users = dailySteps_merged[['Id']].drop_duplicates()
dailySteps_merged_users['dailySteps_merged'] = 1
heartrate_seconds_merged_users = heartrate_seconds_merged[['Id']].drop_duplicates()
heartrate_seconds_merged_users['heartrate_seconds_merged'] = 1
hourlyCalories_merged_users = hourlyCalories_merged[['Id']].drop_duplicates()
hourlyCalories_merged_users['hourlyCalories_merged'] = 1
hourlyIntensities_merged_users = hourlyIntensities_merged[['Id']].drop_duplicates()
hourlyIntensities_merged_users['hourlyIntensities_merged'] = 1
hourlySteps_merged_users = hourlySteps_merged[['Id']].drop_duplicates()
hourlySteps_merged_users['hourlySteps_merged'] = 1
minuteCaloriesNarrow_merged_users = minuteCaloriesNarrow_merged[['Id']].drop_duplicates()
minuteCaloriesNarrow_merged_users['minuteCaloriesNarrow_merged'] = 1
minuteCaloriesWide_merged_users = minuteCaloriesWide_merged[['Id']].drop_duplicates()
minuteCaloriesWide_merged_users['minuteCaloriesWide_merged'] = 1
minuteIntensitiesNarrow_merged_users = minuteIntensitiesNarrow_merged[['Id']].drop_duplicates()
minuteIntensitiesNarrow_merged_users['minuteIntensitiesNarrow_merged'] = 1
minuteIntensitiesWide_merged_users = minuteIntensitiesWide_merged[['Id']].drop_duplicates()
minuteIntensitiesWide_merged_users['minuteIntensitiesWide_merged'] = 1
minuteMETsNarrow_merged_users = minuteMETsNarrow_merged[['Id']].drop_duplicates()
minuteMETsNarrow_merged_users['minuteMETsNarrow_merged'] = 1
minuteSleep_merged_users = minuteSleep_merged[['Id']].drop_duplicates()
minuteSleep_merged_users['minuteSleep_merged'] = 1
minuteStepsNarrow_merged_users = minuteStepsNarrow_merged[['Id']].drop_duplicates()
minuteStepsNarrow_merged_users['minuteStepsNarrow_merged'] = 1
minuteStepsWide_merged_users = minuteStepsWide_merged[['Id']].drop_duplicates()
minuteStepsWide_merged_users['minuteStepsWide_merged'] = 1
sleepDay_merged_users = sleepDay_merged[['Id']].drop_duplicates()
sleepDay_merged_users['sleepDay_merged'] = 1
weightLogInfo_merged_users = weightLogInfo_merged[['Id']].drop_duplicates()
weightLogInfo_merged_users['weightLogInfo_merged'] = 1

all_users = dailyActivity_merged_users.merge(dailyCalories_merged_users, on='Id',how='outer').merge(dailyIntensities_merged_users,on='Id', how='outer').merge(dailySteps_merged_users, on='Id',how='outer')
all_users = all_users.merge(heartrate_seconds_merged_users,on='Id', how='outer').merge(hourlyCalories_merged_users, on='Id',how='outer').merge(hourlyIntensities_merged_users, on='Id',how='outer').merge(hourlySteps_merged_users, on='Id',how='outer')
all_users = all_users.merge(minuteCaloriesNarrow_merged_users, on='Id',how='outer').merge(minuteCaloriesWide_merged_users, on='Id',how='outer').merge(minuteIntensitiesNarrow_merged_users, on='Id',how='outer').merge(minuteIntensitiesWide_merged_users, on='Id',how='outer')
all_users = all_users.merge(minuteMETsNarrow_merged_users, on='Id',how='outer').merge(minuteSleep_merged_users, on='Id',how='outer').merge(minuteStepsNarrow_merged_users, on='Id',how='outer').merge(minuteStepsWide_merged_users, on='Id',how='outer')
all_users = all_users.merge(sleepDay_merged_users, on='Id', how='outer').merge(weightLogInfo_merged_users, on='Id',how='outer')
all_users.fillna(0, inplace=True)

In [27]:
all_users.groupby(['dailyActivity_merged', 'hourlyCalories_merged', 'hourlyIntensities_merged', 'hourlySteps_merged', 'sleepDay_merged', 'weightLogInfo_merged']).Id.nunique().reset_index()

dailyActivity_merged  hourlyCalories_merged  hourlyIntensities_merged  \
0                     1                      1                         1   
1                     1                      1                         1   
2                     1                      1                         1   
3                     1                      1                         1   

   hourlySteps_merged  sleepDay_merged  weightLogInfo_merged  Id  
0                   1              0.0                   0.0   7  
1                   1              0.0                   1.0   2  
2                   1              1.0                   0.0  18  
3                   1              1.0                   1.0   6

> FINDINGS - User availability in data

- There are 33 unique users in total across all data

- All 33 are present in the daily and hourly data

- `weightLogInfo` seem to be the most sparse, hence will not be included in this analysis

- minute data are too granular therefore will not be included in this analysis


## Analyze


#### Daily Activities


In [28]:
#Add day of week into it
dailyActivity_merged['weekday'] = dailyActivity_merged['date'].dt.day_name()

conditions = [(dailyActivity_merged['weekday'] == 'Sunday'),
            (dailyActivity_merged['weekday'] == 'Monday'),
            (dailyActivity_merged['weekday'] == 'Tuesday'),
            (dailyActivity_merged['weekday'] == 'Wednesday'),
            (dailyActivity_merged['weekday'] == 'Thursday'),
            (dailyActivity_merged['weekday'] == 'Friday'),
            (dailyActivity_merged['weekday'] == 'Saturday')]

choices = [7, 1, 2, 3, 4, 5, 6]

dailyActivity_merged['week'] = np.select(conditions, choices)

dailyActivity_merged.head()

Id       date  TotalSteps  TotalDistance  TrackerDistance  \
0  1503960366 2016-04-12       13162           8.50             8.50   
1  1503960366 2016-04-13       10735           6.97             6.97   
2  1503960366 2016-04-14       10460           6.74             6.74   
3  1503960366 2016-04-15        9762           6.28             6.28   
4  1503960366 2016-04-16       12669           8.16             8.16   

   LoggedActivitiesDistance  VeryActiveDistance  ModeratelyActiveDistance  \
0                       0.0                1.88                      0.55   
1                       0.0                1.57                      0.69   
2                       0.0                2.44                      0.40   
3                       0.0                2.14                      1.26   
4                       0.0                2.71                      0.41   

   LightActiveDistance  SedentaryActiveDistance  VeryActiveMinutes  \
0                 6.06                      0.0                 25   
1                 4.71                      0.0                 21   
2                 3.91                      0.0                 30   
3                 2.83                      0.0                 29   
4                 5.04                      0.0                 36   

   FairlyActiveMinutes  LightlyActiveMinutes  SedentaryMinutes  Calories  \
0                   13                   328               728      1985   
1                   19                   217               776      1797   
2                   11                   181              1218      1776   
3                   34                   209               726      1745   
4                   10                   221               773      1863   

     weekday  week  
0    Tuesday     2  
1  Wednesday     3  
2   Thursday     4  
3     Friday     5  
4   Saturday     6

In [29]:
# dailyActivity_merged.groupby('Id').date.size().reset_index().sort_values(['date', 'Id'], ascending=[False, True])
x = dailyActivity_merged.groupby('Id').date.size().reset_index().groupby('date').Id.nunique().reset_index()
x['perc'] = np.round(x['Id']/x['Id'].sum()*100.0, 2)
display(x)


date  Id   perc
0     4   1   3.03
1    18   1   3.03
2    19   1   3.03
3    20   1   3.03
4    26   2   6.06
5    28   1   3.03
6    29   2   6.06
7    30   3   9.09
8    31  21  63.64

- There are 33 users recorded in the `dailyActivity` data.

- 24 users (72%) have tracked their daily activities for 30 days or more


In [30]:
px.box(dailyActivity_merged.select_dtypes([float])).show()
px.box(dailyActivity_merged['TotalSteps']).show()
px.box(dailyActivity_merged[['VeryActiveMinutes', 'FairlyActiveMinutes', 'LightlyActiveMinutes', 'SedentaryMinutes']]).show()
px.box(dailyActivity_merged['Calories']).show()

In [31]:
x = pd.DataFrame({'totalActivityMinutes' :dailyActivity_merged[['VeryActiveMinutes', 'FairlyActiveMinutes', 'LightlyActiveMinutes', 'SedentaryMinutes']].sum(axis=1)})
x['totalActivityMinutes_cat'] = np.where(x['totalActivityMinutes'] == 1440, "1. 1440 minutes (24 hours)", \
    np.where(x['totalActivityMinutes'] > 1440, "2. BAD - More than 24 hours", \
        np.where(x['totalActivityMinutes'] >= 1380, "3. ~23 hours", "4. BAD - Less than 23 hours")))
totalActivityMinutes_prop = x.groupby('totalActivityMinutes_cat').size().reset_index().rename(columns={0:'nrows'})
totalActivityMinutes_prop['x'] = 0

fig = px.bar(totalActivityMinutes_prop, x='x', y='nrows', color='totalActivityMinutes_cat')
fig.show()

> INSIGHTS - Daily Activity Overall Trend

- `TotalDistance` and `TrackerDistance` have very similar distribution, hence we will use `TrackerDistance` in this analysis, as well as because it is the distance tracked by Bellabeat's device.

- `TotalSteps` and `Calories` provides very good description of users' daily activities, trherefore will be one of the main data to be analysed.

- `LoggedActivities` will not be included in this analysis as it is very sparse, hence unusable.

- `ActivityMinutes` are quite unusable, as ~50% of the records are less than 24 hours. Without business insights as to how to treat these records (delete them? treat the missing hours as `SedentaryMinutes`?) it would be unwise to use these fields for the current analysis. We would recommend Bellabeat to implement reminders for users to wear the smart devices and use sleek designs to make its usage more seamless and comfortable.


In [32]:
dailyActivity_merged['StepsCat'] = np.where(dailyActivity_merged['TotalSteps'] < 2000.0, 'HAS_NO_STEPS', 'HAS_STEPS')
users_bysteps = dailyActivity_merged.groupby(['Id', 'StepsCat']).date.nunique().reset_index().pivot(index='Id', columns='StepsCat', values='date').fillna(0.0).reset_index()
users_bysteps['steps_perc'] = users_bysteps['HAS_STEPS']/(users_bysteps['HAS_STEPS']+users_bysteps['HAS_NO_STEPS'])*100//10*10
display(users_bysteps.groupby('steps_perc').Id.nunique().reset_index())

# Let's take a look at records where people hasn't met the min. daily steps according to the CDC (min 2000 steps), but still made some steps. What does the trend look like?
# Source: https://www.healthline.com/health/average-steps-per-day#:~:text=This%20means%20you'll%20need,under%205%2C000%20steps%20per%20day)
nosteps_byday = dailyActivity_merged.query("TotalSteps < 2000.0 & TotalSteps > 100").groupby(['week', 'weekday']).agg(
    min_steps=('TotalSteps', np.min), 
    mean_steps=('TotalSteps', np.mean), 
    median_steps=('TotalSteps', np.median), 
    max_steps=('TotalSteps', np.max),
    dates=('date', 'nunique'),
    nrows=('Id', 'size'), 
    ndays=('date', 'nunique')
).reset_index()

nosteps_byday['noccurence_perday'] = nosteps_byday['nrows']/nosteps_byday['ndays']
display(nosteps_byday)

# Now let's take a look at people who made steps (at least 2000).
steps_byday = dailyActivity_merged.query("TotalSteps > 2000.0").groupby(['week', 'weekday']).agg(
    min_steps=('TotalSteps', np.min), 
    mean_steps=('TotalSteps', np.mean), 
    median_steps=('TotalSteps', np.median), 
    max_steps=('TotalSteps', np.max),
    dates=('date', 'nunique'),
    nusers=('Id', 'nunique')
    ).reset_index()

# steps_byday['noccurence_perday'] = nosteps_byday['size']/nosteps_byday['nunique']
display(steps_byday)


steps_perc  Id
0        20.0   1
1        30.0   2
2        40.0   1
3        50.0   1
4        70.0   1
5        80.0   4
6        90.0  16
7       100.0   7

week    weekday  min_steps   mean_steps  median_steps  max_steps  dates  \
0     1     Monday        152  1067.166667        1103.5       1969      4   
1     2    Tuesday        197   755.200000         678.0       1326      5   
2     3  Wednesday        356  1276.375000        1324.5       1786      4   
3     4   Thursday        108   951.300000         993.5       1675      4   
4     5     Friday        149  1195.000000        1282.0       1882      4   
5     6   Saturday        244  1462.166667        1689.0       1982      3   
6     7     Sunday        400  1064.000000        1004.0       1807      3   

   nrows  ndays  noccurence_perday  
0      6      4           1.500000  
1      5      5           1.000000  
2      8      4           2.000000  
3     10      4           2.500000  
4      9      4           2.250000  
5      6      3           2.000000  
6      8      3           2.666667

week    weekday  min_steps   mean_steps  median_steps  max_steps  dates  \
0     1     Monday       2276  9002.320388        8382.0      20500      4   
1     2    Tuesday       2064  9327.393939        9457.5      23186      5   
2     3  Wednesday       2072  8710.720930        8367.0      23629      5   
3     4   Thursday       2163  8845.311475        8850.5      21129      5   
4     5     Friday       2091  8510.422018        8198.0      21727      4   
5     6   Saturday       2104  9454.386792        8015.0      29326      4   
6     7     Sunday       2090  8303.640000        7363.5      36019      4   

   nusers  
0      31  
1      33  
2      32  
3      32  
4      33  
5      32  
6      31

> INSIGHTS - Daily Steps

- Only 7 out 33 users (21%) have made more steps than the CDC's min threshold (2,000 steps, [source](https://www.healthline.com/health/average-steps-per-day#:~:text=This%20means%20you'll%20need,under%205%2C000%20steps%20per%20day)) every day (100%) during the entire time period. **Thursday**, **Friday**, and **Sunday** seems to be the days with the most occurence of not reaching the CDC's min guideline by users.

- Users who do not reach the minimum daily steps seems to be way behind. This is a challenge and an opportunity for Bellabeat to motivate their users to take more daily steps and better themselves. Bellabeat can consider reminders or even gamification to motivate their users. They can start by motivating them on **Wednesday** and **Saturday** as it is the quickest win compared to other days.

- Workday seems to be where users get their steps more done whilst meeting the min. steps according to the CDC. With **Tuesday** taking the top spot of day with most steps, and **Sunday** being the slowest day

- Overall, Sundays seem to be the most 'laziest' day in terms of getting daily steps. Tuesday is the most 'active' day, followed by Thursday


In [33]:
# Overall Calories expenditure by day
overall_calories_byday = dailyActivity_merged.groupby(['week', 'weekday']).agg(
    min_calories=('Calories', np.min),
    mean_calories=('Calories', np.mean),
    median_calories=('Calories', np.median),
    max_calories=('Calories', np.max),
    nusers=('Id', 'nunique')
).reset_index()

display(overall_calories_byday)

# Women who don't spend 1600 daily calories (Source: https://www.healthline.com/health/fitness-exercise/how-many-calories-do-i-burn-a-day#:~:text=Most%20female%20adults%20need%201%2C600,breathing). What does the trend look like?
nocalories_byday = dailyActivity_merged.query("Calories < 1600").groupby(['week', 'weekday']).agg(
    min_calories=('Calories', np.min),
    mean_calories=('Calories', np.mean),
    median_calories=('Calories', np.median),
    max_calories=('Calories', np.max),
    nusers=('Id', 'nunique'),
    nrow=('Id', 'size')
).reset_index()

display(nocalories_byday)

# Women who do spend the minimum daily calories, what is the trend for each day?
calories_byday = dailyActivity_merged.query("Calories >= 1600").groupby(['week', 'weekday']).agg(
    min_calories=('Calories', np.min),
    mean_calories=('Calories', np.mean),
    median_calories=('Calories', np.median),
    max_calories=('Calories', np.max),
    nusers=('Id', 'nunique'),
    nrow=('Id', 'size')
).reset_index()

display(calories_byday)


week    weekday  min_calories  mean_calories  median_calories  \
0     1     Monday          1248    2324.208333           2182.0   
1     2    Tuesday             0    2356.013158           2229.0   
2     3  Wednesday            52    2302.620000           2143.0   
3     4   Thursday             0    2199.571429           2065.0   
4     5     Friday           403    2331.785714           2203.5   
5     6   Saturday             0    2354.967742           2127.5   
6     7     Sunday          1214    2263.000000           2063.0   

   max_calories  nusers  
0          4157      32  
1          4092      33  
2          4079      33  
3          4900      33  
4          4044      33  
5          4547      32  
6          4552      32

week    weekday  min_calories  mean_calories  median_calories  \
0     1     Monday          1248    1437.750000           1455.5   
1     2    Tuesday             0    1258.722222           1397.5   
2     3  Wednesday            52    1378.750000           1436.0   
3     4   Thursday             0    1196.000000           1383.0   
4     5     Friday           403    1369.785714           1427.0   
5     6   Saturday             0    1223.000000           1463.0   
6     7     Sunday          1214    1444.055556           1455.5   

   max_calories  nusers  nrow  
0          1584       5    12  
1          1595       7    18  
2          1593       9    20  
3          1589      20    31  
4          1590       7    14  
5          1574       8    13  
6          1593       9    18

week    weekday  min_calories  mean_calories  median_calories  \
0     1     Monday          1604    2422.703704           2259.0   
1     2    Tuesday          1604    2503.410448           2345.0   
2     3  Wednesday          1628    2444.753846           2294.0   
3     4   Thursday          1610    2467.767241           2279.0   
4     5     Friday          1632    2452.035714           2305.0   
5     6   Saturday          1625    2487.540541           2180.0   
6     7     Sunday          1617    2406.116505           2246.0   

   max_calories  nusers  nrow  
0          4157      32   108  
1          4092      32   134  
2          4079      33   130  
3          4900      32   116  
4          4044      30   112  
5          4547      32   111  
6          4552      31   103

> INSIGHTS - Daily Calories

- Overall, users are actually spending the recommended amount of daily calories.

- Women who don't spend the recommended min calories (1600 cal, [Source](https://www.healthline.com/health/fitness-exercise/how-many-calories-do-i-burn-a-day#:~:text=Most%20female%20adults%20need%201%2C600,breathing)) are actually quite close to getting to the minimum expenditure, every day. Bellabeat can perhaps include programs to give a little nudge to their users to spend a little more calories. For instance a loyalty program in which the users would need to have at least 14 consecutive days of spending the min. amount of daily calories to enable certain benefits/features. The higher the number of consecutive days, the better the benefit.


In [34]:
px.scatter(dailyActivity_merged, x='TotalSteps', y='TrackerDistance', trendline='ols', trendline_color_override="red", title='Steps vs Distance (km)')

In [35]:
fig = px.scatter(dailyActivity_merged.query("StepsCat == 'HAS_STEPS' & TotalSteps < 25000"), \
    x='TotalSteps', y='Calories', trendline='ols', trendline_color_override="red", title='Steps vs Calories')
fig.show()

trendline = px.get_trendline_results(fig).iloc[0]["px_fit_results"].params
print("Slope of line {:.2f}".format(trendline[1]))

Slope of line 0.08


In [36]:
dailyActivity_merged.query("StepsCat == 'HAS_STEPS' & TotalSteps < 25000")[['TotalSteps', 'Calories']].to_clipboard()

> INSIGHTS - Daily Steps & Calories Relationship

Here we can definitely see a popsitive correlation between steps taken and calories burned. The more active users are, the more calories they burn.

#### Hourly Activities


In [37]:
hourly_merged.query('Hour == 0 & StepTotal > 0')

Id   datetime  StepTotal  Calories  TotalIntensity  \
0      1503960366 2016-04-12        373        81              20   
24     1503960366 2016-04-13        144        69              14   
48     1503960366 2016-04-14         81        56               4   
72     1503960366 2016-04-15         83        60               6   
96     1503960366 2016-04-16        459        77              15   
...           ...        ...        ...       ...             ...   
21172  8792009665 2016-05-02        351       131              15   
21196  8792009665 2016-05-03        130       113              11   
21220  8792009665 2016-05-04        337       134              17   
21460  8877689391 2016-04-16        600       143              20   
21484  8877689391 2016-04-17       2128       244              41   

       AverageIntensity  Hour    weekday  week   week_label weektype  
0              0.333333     0    Tuesday     2    2-Tuesday  WEEKDAY  
24             0.233333     0  Wednesday     3  3-Wednesday  WEEKDAY  
48             0.066667     0   Thursday     4   4-Thursday  WEEKDAY  
72             0.100000     0     Friday     5     5-Friday  WEEKDAY  
96             0.250000     0   Saturday     6   6-Saturday  WEEKEND  
...                 ...   ...        ...   ...          ...      ...  
21172          0.250000     0     Monday     1     1-Monday  WEEKDAY  
21196          0.183333     0    Tuesday     2    2-Tuesday  WEEKDAY  
21220          0.283333     0  Wednesday     3  3-Wednesday  WEEKDAY  
21460          0.333333     0   Saturday     6   6-Saturday  WEEKEND  
21484          0.683333     0     Sunday     7     7-Sunday  WEEKEND  

[301 rows x 11 columns]

In [38]:
hourly_steps = hourly_merged.groupby('Hour').agg(mean=('StepTotal', np.mean), median=('StepTotal', np.median)).reset_index()
hourly_steps = pd.melt(hourly_steps, id_vars='Hour', value_vars=['mean', 'median'])
px.line(hourly_steps, x='Hour', y='value', title='Avg & Median Hourly Total Steps', color='variable').show()

hourly_steps_day_median = hourly_merged.groupby(['weektype', 'Hour']).agg( median=('StepTotal', np.median)).reset_index()
hourly_steps_day_median = pd.melt(hourly_steps_day_median, id_vars=['weektype', 'Hour'], value_vars=['median'])
px.line(hourly_steps_day_median, x='Hour', y='value', title='Median Hourly Total Steps by Week Type', color='weektype').show()

hourly_steps_day_mean = hourly_merged.groupby(['weektype', 'Hour']).agg( mean=('StepTotal', np.mean)).reset_index()
hourly_steps_day_mean = pd.melt(hourly_steps_day_mean, id_vars=['weektype', 'Hour'], value_vars=['mean'])
px.line(hourly_steps_day_mean, x='Hour', y='value', title='Avg Hourly Total Steps by Week Type', color='weektype').show()

> INSIGHTS - Hourly Steps Trend

- We can see that overall, our users are taking the most steps at 18 o'clock in the evening, and started taking their steps at 7 o'clock.

- If we break it down by week type, we can see that during weekdays, user's steps peak at 18 o'clock, and during weekdays they peak 13-14 o'clock. 

- However, during weekends, users don't start to take their steps until 9 o'clock (compared to 7 o'clock during weekdays). Bellabeat can create morning programs to motivate users to start taking their steps earlier during the weekends to promote healthier lifestyles.

- We can see that the median and average trends differs in magnitude. This shows that there are several users who take more steps in certain hours that the norm. Bellabeat can consider to partner with these power users to promote healthier lifestyles. They can also segment the users based on this trend to give personalized content/fitness program/etc.

In [39]:
hourly_cals = hourly_merged.groupby('Hour').agg(mean=('Calories', np.mean), median=('Calories', np.median)).reset_index()
hourly_cals = pd.melt(hourly_cals, id_vars='Hour', value_vars=['mean', 'median'])
px.line(hourly_cals, x='Hour', y='value', title='Avg & Median Hourly Total Calories Exp', color='variable').show()

hourly_cals_day_median = hourly_merged.groupby(['weektype', 'Hour']).agg( median=('Calories', np.median)).reset_index()
hourly_cals_day_median = pd.melt(hourly_cals_day_median, id_vars=['weektype', 'Hour'], value_vars=['median'])
px.line(hourly_cals_day_median, x='Hour', y='value', title='Median Hourly Total Calories Exp by Week Type', color='weektype').show()

hourly_cals_day_mean = hourly_merged.groupby(['weektype', 'Hour']).agg( mean=('Calories', np.mean)).reset_index()
hourly_cals_day_mean = pd.melt(hourly_cals_day_mean, id_vars=['weektype', 'Hour'], value_vars=['mean'])
px.line(hourly_cals_day_mean, x='Hour', y='value', title='Avg Hourly Total Calories Exp by Week Type', color='weektype').show()

> INSIGHTS - Hourly Calories Expenditures

- Consistent with the Total Steps, Calory expenditure peaks at 18 o'clock overall (13-14 o'clock during weekends, 18 o'clock during weekdays)

- During the weekday, avg calory exp starts to rise at 5 o'clock (likely workout or exercise). This is likely due to power users (comparing to the median, it is flat, hence it is due to power users, not the norm). Bellabeat can be more certain that with this type of data, they can determine who worksout/exercises in the morning and who don't. From this, Bellabeat can segment these customers and give personalized content/workout programs/etc.

`TotalIntensity` is gained by adding all the minute-level intensity values that occurred within the hour. This poses a challenge as there is yet no clear interpretation of the value and in need of subject expert input. For instance, say the Total Intensity for the hour is 3. This could be attained by adding intensity score 0 and 3, as well as 1 and 2. So which combination of intensity is better? For this reason, we have chosen not to analyze this feature yet.

##### Creating User Segmentation based on their Hourly Steps

**Background**

Bellabeat can certainly segment their users based on their activities. It can be usign daily or hourly data. Here, it is recommended that we use hourlyd ata as it is more granular and gives a clearer picture of how the users spends their day. We can use the number of steps, calories, and activities. However, due to data limitations, we do not have the list of activities taken by users hence cannot determine exactly how or why their calory expenditures are as the data shows. So, for this analysis, we will use **steps per hour** as the indicator to segment Bellabeat's users.

In [40]:
nrows_hourlysteps = hourly_merged.groupby('Id').datetime.nunique().reset_index().sort_values(by='datetime')
nrows_hourlysteps.head(5).append(nrows_hourlysteps.tail(5))

C:\Users\User\AppData\Local\Temp\ipykernel_14676\490107202.py:2: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.



Id  datetime
13  4057192912        88
8   2347167796       414
28  8253242879       431
10  3372868164       472
25  7007744171       601
6   2026352035       736
5   2022484408       736
4   1927972279       736
1   1624580081       736
17  4558609924       736

Irrelevant and Missing Hours

We can see that we do not have a full 31 days and 24 hours of data (744 hours, or in this case, number of rows). This is likely because users do not use the device 24/7 which is perfectly normal. However, to have a "fair" segment, we need to treat everybody with the same set of standards. It would not be fair to segment someone with only 88 hours of data with someone who has 736 hours. We need to put everyone into a full 744 records.

But we also do not want irrelevant hours tot ake steps (e.g., 0-4 o'clock). Because this will likely be 0 (how often someones takes long walks in these hours, right?)

In [41]:
hourly_steps = hourly_merged[['datetime', 'Id', 'StepTotal']]
hours = pd.DataFrame({'datetime':pd.date_range(hourly_merged.datetime.min(), pd.to_datetime('2016-05-12 23:00:00'), freq='H')})
hourly_steps = hourly_steps[['Id']].drop_duplicates().merge(hours, how='cross').merge(hourly_steps, on=['Id', 'datetime'], how='left').fillna(0)
hourly_steps['hour'] = hourly_steps.datetime.dt.hour
hourly_steps = hourly_steps.query('hour > 4')
hourly_steps.head()

Id            datetime  StepTotal  hour
5  1503960366 2016-04-12 05:00:00        0.0     5
6  1503960366 2016-04-12 06:00:00        0.0     6
7  1503960366 2016-04-12 07:00:00        0.0     7
8  1503960366 2016-04-12 08:00:00      250.0     8
9  1503960366 2016-04-12 09:00:00     1864.0     9

In [42]:
nrows_hourlysteps = hourly_steps.groupby('Id').datetime.nunique().reset_index().sort_values(by='datetime')
nrows_hourlysteps.head(5).append(nrows_hourlysteps.tail(5))

C:\Users\User\AppData\Local\Temp\ipykernel_14676\2823746791.py:2: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.



Id  datetime
0   1503960366       589
30  8583815059       589
29  8378563200       589
28  8253242879       589
27  8053475328       589
3   1844505072       589
2   1644430081       589
1   1624580081       589
15  4388161847       589
32  8877689391       589

Create the segments

Now that we have full 31 day adn 19 hour records for each user, we can create a segment. From the boxplot below, we can see that trend of average hourly steps in a month. We can make 3 separate segments for these users (`active`, `medium`, and `light` users). The threshold for each segments are based on the boxplot below. 

With this new user segment, Bellabeat can begin to personalize their marketing and content to each of their users. 

In [43]:
user_segments = hourly_steps.groupby('Id').agg(avg_hourly_steps_in_month=('StepTotal', np.mean)).reset_index()
px.box(user_segments, y='avg_hourly_steps_in_month')

In [44]:
user_segments['segment'] = np.where(user_segments['avg_hourly_steps_in_month'] > 488.43, 'ACTIVE', \
    np.where(user_segments['avg_hourly_steps_in_month'] > 231.57, 'MEDIUM', 'LIGHT'))
user_segments_smy = user_segments.groupby('segment').Id.nunique().reset_index()
user_segments_smy['perc'] = user_segments_smy['Id']/user_segments_smy['Id'].sum()
px.pie(user_segments_smy, values='perc', names='segment', title='Bellabeat User Segments by Hourly Steps')

In [45]:
fig = px.scatter(hourly_merged.query("StepTotal > 0 "), \
    x='StepTotal', y='Calories', trendline='ols', trendline_color_override="red", title='Steps vs Calories')
fig.show()

trendline = px.get_trendline_results(fig).iloc[0]["px_fit_results"].params
print("Slope of line {:.2f}".format(trendline[1]))

Slope of line 0.07


> Hourly Steps and Calories

- Similar to the daily steps vs calories, there is of course positive correlation between the daily steps and calories with similar slope-of-line. 



#### Sleep


In [46]:
# Add Hours columns to sleepDay_merged to make analysis much easier
sleepDay_merged['TotalHoursAsleep'] = sleepDay_merged['TotalMinutesAsleep']/60.0
sleepDay_merged['TotalHoursInBed'] = sleepDay_merged['TotalTimeInBed']/60.

#Add difference of Hours Asleep with Hours in Bed
sleepDay_merged['sleep_bed_diff'] = sleepDay_merged['TotalHoursInBed'] - sleepDay_merged['TotalHoursAsleep']

#Add day of week into it
sleepDay_merged['weekday'] = sleepDay_merged['datetime'].dt.day_name()

conditions = [(sleepDay_merged['weekday'] == 'Sunday'),
            (sleepDay_merged['weekday'] == 'Monday'),
            (sleepDay_merged['weekday'] == 'Tuesday'),
            (sleepDay_merged['weekday'] == 'Wednesday'),
            (sleepDay_merged['weekday'] == 'Thursday'),
            (sleepDay_merged['weekday'] == 'Friday'),
            (sleepDay_merged['weekday'] == 'Saturday')]

choices = [7, 1, 2, 3, 4, 5, 6]

sleepDay_merged['week'] = np.select(conditions, choices)

sleepDay_merged.head()

Id   datetime  TotalSleepRecords  TotalMinutesAsleep  \
0  1503960366 2016-04-12                  1                 327   
1  1503960366 2016-04-13                  2                 384   
2  1503960366 2016-04-15                  1                 412   
3  1503960366 2016-04-16                  2                 340   
4  1503960366 2016-04-17                  1                 700   

   TotalTimeInBed  TotalHoursAsleep  TotalHoursInBed  sleep_bed_diff  \
0             346          5.450000         5.766667        0.316667   
1             407          6.400000         6.783333        0.383333   
2             442          6.866667         7.366667        0.500000   
3             367          5.666667         6.116667        0.450000   
4             712         11.666667        11.866667        0.200000   

     weekday  week  
0    Tuesday     2  
1  Wednesday     3  
2     Friday     5  
3   Saturday     6  
4     Sunday     7

In [47]:
x = sleepDay_merged.groupby('Id').datetime.nunique().reset_index().groupby('datetime').Id.nunique().reset_index()
x['perc'] = np.round(x['Id']/x['Id'].sum()*100)
print(x.Id.sum())
display(x)

24


datetime  Id  perc
0          1   1   4.0
1          2   1   4.0
2          3   3  12.0
3          4   1   4.0
4          5   2   8.0
5          8   1   4.0
6         15   2   8.0
7         18   1   4.0
8         23   1   4.0
9         24   1   4.0
10        25   1   4.0
11        26   2   8.0
12        27   1   4.0
13        28   3  12.0
14        31   3  12.0

Only 24 users has ther sleep data recorded. And 24% of those users (6 Ids) recorded at least 28 days of data.


In [48]:
x = sleepDay_merged.groupby('Id').TotalSleepRecords.mean().reset_index().groupby('TotalSleepRecords').Id.nunique().reset_index()
x['perc'] = np.round(x['Id']/x['Id'].sum()*100)
display(x)
x = sleepDay_merged.groupby('Id').agg({'TotalSleepRecords': np.mean, 'datetime': 'size'}).reset_index().sort_values('TotalSleepRecords', ascending=False).head(5)
x.rename(columns={'TotalSleepRecords':'Avg_TotalSleepRecords', 'datetime':'ndays'}, inplace=True)
display(x)

TotalSleepRecords  Id  perc
0            1.000000  12  50.0
1            1.038462   2   8.0
2            1.074074   1   4.0
3            1.080000   1   4.0
4            1.096774   1   4.0
5            1.129032   1   4.0
6            1.142857   1   4.0
7            1.222222   1   4.0
8            1.225806   1   4.0
9            1.304348   1   4.0
10           1.392857   1   4.0
11           1.600000   1   4.0

Id  Avg_TotalSleepRecords  ndays
3   1927972279               1.600000      5
11  4445114986               1.392857     28
10  4388161847               1.304348     23
14  5553957443               1.225806     31
16  6117666160               1.222222     18

About 12 users (50% of users) of the sample users who tracked their sleep, sleeps only once during the sample timespan. The other 50% has slept more than once in at least one day during this time period.


In [49]:
display(sleepDay_merged.agg({'TotalHoursAsleep': [np.min, np.mean, np.median, np.max], \
    'TotalHoursInBed': [np.min, np.mean, np.median, np.max], \
    'sleep_bed_diff': [np.min, np.mean, np.median, np.max]}).reset_index())
display(sleepDay_merged.groupby('Id').agg({'TotalHoursAsleep': ['size', np.min, np.mean, np.median, np.max], \
    'TotalHoursInBed': [np.min, np.mean, np.median, np.max], \
    'sleep_bed_diff': [np.min, np.mean, np.median, np.max]}).reset_index())
x = sleepDay_merged.query('TotalHoursAsleep < 7')
print("{} users have slept less than 7 hours at least once in the time span".format(x.Id.nunique()))
x = sleepDay_merged.query('TotalHoursAsleep < 3')
print("{} users have slept less than 3 hours at least once in the time span".format(x.Id.nunique()))
x = sleepDay_merged.groupby('Id').TotalHoursAsleep.mean().reset_index().query('TotalHoursAsleep < 7.0')
print("{} users have slept on average less than 7 hours in the time span".format(x.Id.nunique()))
x = sleepDay_merged.groupby('Id').TotalHoursAsleep.mean().reset_index().query('TotalHoursAsleep < 3.0')
print("{} users have slept on average less than 3 hours in the time span".format(x.Id.nunique()))

index  TotalHoursAsleep  TotalHoursInBed  sleep_bed_diff
0    amin          0.966667         1.016667        0.000000
1    mean          6.986220         7.641382        0.655163
2  median          7.208333         7.716667        0.425000
3    amax         13.266667        16.016667        6.183333

Id TotalHoursAsleep                                             \
                           size      amin       mean     median       amax   
0   1503960366               25  4.083333   6.004667   5.666667  11.666667   
1   1644430081                4  1.983333   4.900000   2.175000  13.266667   
2   1844505072                3  9.833333  10.866667  10.733333  12.033333   
3   1927972279                5  2.766667   6.950000   6.633333  12.500000   
4   2026352035               28  5.950000   8.436310   8.608333   9.550000   
5   2320127002                1  1.016667   1.016667   1.016667   1.016667   
6   2347167796               15  6.233333   7.446667   7.416667   9.266667   
7   3977333714               28  2.533333   4.894048   4.858333   7.066667   
8   4020332650                8  1.283333   5.822917   6.241667   8.350000   
9   4319703577               26  0.983333   7.944231   8.225000  11.533333   
10  4388161847               23  1.033333   6.669565   7.133333  10.316667   
11  4445114986               28  1.633333   6.419643   6.716667   8.366667   
12  4558609924                5  1.716667   2.126667   2.050000   2.850000   
13  4702921684               27  4.216667   6.958025   7.016667   9.850000   
14  5553957443               31  5.366667   7.724731   7.300000  12.916667   
15  5577150313               26  1.233333   7.200000   7.125000  10.050000   
16  6117666160               18  5.600000   7.979630   8.200000  10.966667   
17  6775888955                3  3.916667   5.827778   6.516667   7.050000   
18  6962181067               31  4.966667   7.466667   7.366667  10.500000   
19  7007744171                2  0.966667   1.141667   1.141667   1.316667   
20  7086361926               24  5.366667   7.552083   7.516667  11.350000   
21  8053475328                3  1.233333   4.950000   5.516667   8.100000   
22  8378563200               31  5.383333   7.418817   7.350000  10.183333   
23  8792009665               15  5.650000   7.261111   7.050000   8.850000   

   TotalHoursInBed                                  sleep_bed_diff            \
              amin       mean     median       amax           amin      mean   
0         4.400000   6.386667   6.116667  11.866667       0.066667  0.382000   
1         2.116667   5.766667   2.466667  16.016667       0.133333  0.866667   
2        16.016667  16.016667  16.016667  16.016667       3.983333  5.150000   
3         2.966667   7.296667   7.033333  12.916667       0.200000  0.346667   
4         6.333333   8.960714   9.091667  10.116667       0.166667  0.524405   
5         1.150000   1.150000   1.150000   1.150000       0.133333  0.133333   
6         6.433333   8.188889   8.150000  10.033333       0.200000  0.742222   
7         5.083333   7.685714   7.800000  10.433333       1.766667  2.791667   
8         1.283333   6.329167   6.750000   9.016667       0.000000  0.506250   
9         1.083333   8.366026   8.608333  12.033333       0.100000  0.421795   
10        1.083333   7.053623   7.633333  10.683333       0.050000  0.384058   
11        1.783333   6.947024   7.183333   9.033333       0.033333  0.527381   
12        2.016667   2.333333   2.233333   2.983333       0.133333  0.206667   
13        4.283333   7.303704   7.316667  10.200000       0.066667  0.345679   
14        5.883333   8.431183   7.833333  14.050000       0.333333  0.706452   
15        1.300000   7.676923   7.658333  10.566667       0.066667  0.476923   
16        5.833333   8.502778   8.600000  11.633333       0.150000  0.523148   
17        4.333333   6.150000   6.766667   7.350000       0.250000  0.322222   
18        5.566667   7.768817   7.616667  11.316667       0.033333  0.302151   
19        1.016667   1.191667   1.191667   1.366667       0.050000  0.050000   
20        5.550000   7.773611   7.700000  11.733333       0.016667  0.221528   
21        1.250000   5.027778   5.616667   8.216667       0.016667  0.077778   
22        5.916667   8.098925   7.950000  11.483333       0.233

23 users have slept less than 7 hours at least once in the time span
12 users have slept less than 3 hours at least once in the time span
13 users have slept on average less than 7 hours in the time span
3 users have slept on average less than 3 hours in the time span


We can see the amount of hours each users have spend each day as well as the hours in bed. Almost all users (23) have slept less than 7 hours. And almost half (12 users) have slept only less than 3 hours. On average across the entire time span of daa collection, there are 12 users (50%) who slept less than 7 hours and 3 of them only slept 3 hours on average.

We can also see the difference of hours spent on bed vs actual sleep. On average, users spent _half an hour_ more in bed. There also seems to be an anomaly in one of the users time spent in bed vs sleep. User `3977333714` and `1844505072` spends an additional 2.7 hours and 5 hours, respectively, in bed on average ! These users could be babies, or it could be an indicator of bad sleep habits, or cases of insomnia, which Bellabeat could potentially help in. Another possibility is that these could just be bad data records. Either way, it warants a deeper dive into these users' data and device.

> IMPORTANT: **This analysis shows that users are having trouble getting the adequate amount of sleep**


In [50]:
fig = go.Figure()

fig.add_trace(go.Box(y=sleepDay_merged.TotalHoursAsleep, x=sleepDay_merged.week.astype(str)+ "-" +sleepDay_merged.weekday, name='Tot Hours Sleep'))
fig.add_trace(go.Box(y=sleepDay_merged.TotalHoursInBed, x=sleepDay_merged.week.astype(str)+ "-" +sleepDay_merged.weekday, name='Tot Hours In Bed'))
fig.update_layout(boxmode='group')
fig.update_xaxes(categoryorder='category ascending')
fig.show()

Regarding the sleep patterns by day, we found:

> On avereage, **Saturdays and Sundays** are, understandably, the days in which users both spend time in bed and sleep the most. Interestingly, **Wednesday** comes close after. This can be investigated further as to why users are sleeping as much as the weekends in the middle of workdays. Is this because of exhaustion from work? bad diet? or simply the norm?


#### Sleep + Daily Activities


In [63]:
user_sleep = sleepDay_merged.groupby('Id').datetime.nunique().reset_index()
user_activities = dailyActivity_merged.groupby('Id').date.nunique().reset_index()

user_combined = sleepDay_merged[['Id', 'datetime', 'TotalHoursAsleep', 'TotalHoursInBed']].merge(dailyActivity_merged[['Id', 'date', 'TotalSteps', 'TotalDistance', 'Calories', 'weekday', 'week']], 
    left_on=['Id', 'datetime'], 
    right_on=['Id', 'date'], how='outer').merge(user_segments[['Id', 'segment']], on='Id', how='left')
# user_combined.columns = ['Id', 'sleep', 'activities']

user_combined_smy = user_combined[~user_combined.TotalHoursInBed.isnull()].groupby(['segment']).agg(
    hours_sleep = ('TotalHoursAsleep', np.mean),
    hours_bed = ('TotalHoursInBed', np.mean),
    steps = ('TotalSteps', np.mean),
    calories = ('Calories', np.mean),
).reset_index()

user_combined_smy

segment  hours_sleep  hours_bed         steps     calories
0  ACTIVE     6.153125   7.101786  11153.053571  2128.839286
1   LIGHT     6.895714   7.663333   3939.428571  2442.800000
2  MEDIUM     7.353042   7.868251   8000.346008  2493.091255

In [61]:
px.scatter(user_combined[~user_combined.TotalHoursInBed.isnull()], x='TotalSteps', y='TotalHoursAsleep', trendline='ols', trendline_scope = 'overall', trendline_color_override="red", title='Steps vs Sleep').show()
px.scatter(user_combined[~user_combined.TotalHoursInBed.isnull()], x='Calories', y='TotalHoursAsleep', trendline='ols', trendline_scope = 'overall', trendline_color_override="red", title='Calories vs Sleep').show()

> INSIGHTS - Activities + Sleep

- If we take a look at the overall activities (steps, calories burned) and sleep of each of our segments (excluding the users which do not have sleep data). We can see that despite taking more steps, the `active` segment's calories and amount of sleep are actually the worst. It turns out, MORE STEPS != BETTER SLEEP AND CALORY BURNT. The amount of steps alone cannot, and should not, be used as a sole predictor for gauging users' health. This should be a motivation for Bellabeat to gather more activity data (e.g. did users workout that hour/day) to gain a better view of users health and the driving force behind it.

- Users who despite taking more steps (5k above) they have very little amount of sleep. This is of course dangerous, Bellabeat can help users like these by recommending them sleep pills, or healthy activity programs to tackle their insomniac. And with additional activity data, Bellabeat can recommend better activities/exercise program to help these users' lives to be better.

- No correlation between calory expenditure with amount of sleep during the day. However, we can see several instances in which user burn little calories, and still take less than 7 hours of sleep. This could be the most dangerous health style of all. Bellabeat can quickly identify these users and recommend some correctional courses of actions for the users. 

#### Save the cleaned files


In [53]:
files_clean = [f.replace("/data/", "/data_cleaned/") for f in files]
dailyActivity_merged.to_csv(files_clean[0])
dailyCalories_merged.to_csv(files_clean[1])
dailyIntensities_merged.to_csv(files_clean[2])
dailySteps_merged.to_csv(files_clean[3])
heartrate_seconds_merged.to_csv(files_clean[4])
hourlyCalories_merged.to_csv(files_clean[5])
hourlyIntensities_merged.to_csv(files_clean[6])
hourlySteps_merged.to_csv(files_clean[7])
minuteCaloriesNarrow_merged.to_csv(files_clean[8])
minuteCaloriesWide_merged.to_csv(files_clean[9])
minuteIntensitiesNarrow_merged.to_csv(files_clean[10])
minuteIntensitiesWide_merged.to_csv(files_clean[11])
minuteMETsNarrow_merged.to_csv(files_clean[12])
minuteSleep_merged.to_csv(files_clean[13])
minuteStepsNarrow_merged.to_csv(files_clean[14])
minuteStepsWide_merged.to_csv(files_clean[15])
sleepDay_merged.to_csv(files_clean[16])
weightLogInfo_merged.to_csv(files_clean[17])

## Recommendations

Based on the the data provided, we have seen various trends of smart device usages from 33 users. Some data were more complete than others. The usage of smart devices are indeed beneficial, and as seen in this analysis, crucial, for monitoring users health based on their activities and sleep patterns. The rate of smart device usages is quite good, as 72% of users in this sample have used it to track their activities for 30 days. And it could be better.

We have shown various interesting trends of users' activities and sleep. We also established a user segment to better determine which solutions or course of actions should be taken for these users. All of which could help Bellabeat understand their users and come up with accurate marketing and product decisions. A list of solutions ranging from personalized health and exercise program, a quick health warning system, how to start a loyalty program that is progressed through increase in healthy activities, and in turn, more data to be analyzed, were also provided.

Speaking of data, we have also recommended various steps to help Bellabeat get more data from their users by including reminders and gamifications to wear the devices, adding more activity inputs and sensors (e.g. the ability to enable the device to automatically detect whether or not the user working out/sitting/etc. ), and use of sleek design to make smart device usages more seamless and non-intrusive.

In order for Bellabeat to gain dominance in smart devices market, we these solutions to be low hanging fruits that can boost Bellabeat's market share and loyalty. 